name: Visit Websites Every Day

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 运行一次
  workflow_dispatch: # 启用手动触发

jobs:
  visit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Puppeteer dependencies
      run: sudo apt-get install -y libx11-xcb1 libxcomposite1 libxdamage1 libxi6 libxext6 libxfixes3 libnss3 libasound2 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libdbus-1-3 libgbm1 libgtk-3-0 libxrandr2 libxss1 libxtst6

    - name: Install Puppeteer
      run: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false npm install puppeteer

    - name: Run visitWebsite.js
      run: node ./visit-website/visitWebsite.js
