name: Visit Websites Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟运行一次

jobs:
  visit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Puppeteer dependencies
      run: sudo apt-get install -y libx11-xcb1 libxcomposite1 libxdamage1 libxi6 libxext6 libxfixes3 libnss3 libasound2 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libdbus-1-3 libgbm1 libgtk-3-0

    - name: Install Puppeteer
      run: npm install puppeteer

    - name: Run visitWebsite.js
      run: node ./visit-website/visitWebsite.js
