name: Visit Websites Every Day

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟运行一次

jobs:
  visit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Puppeteer
      run: npm install puppeteer

    - name: Visit Websites
      run: |
        const puppeteer = require('puppeteer');

        (async () => {
          const browser = await puppeteer.launch();
          const page = await browser.newPage();

          await page.goto('https://media.ailoha.com');
          await page.waitForTimeout(60000); // Wait for 5 seconds

          await page.goto('https://bids.ailoha.com');
          await page.waitForTimeout(60000); // Wait for 5 seconds

          await page.goto('https://odi-demo.vercel.app');
          await page.waitForTimeout(60000); // Wait for 5 seconds

          await browser.close();
        })();
